# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from . import constants, core, data_preparation
from matplotlib.patches import Rectangle
from typing import Any, Optional, Tuple
import calendar
import matplotlib.pyplot
import numpy
import pandas
import seaborn

def plot_gender_distribution(customer_df: Any, cust_segment: Any) -> Any:
    ...

def plot_age_distribution(customer_df: Any, cust_segment: Any) -> Any:
    ...

def plot_order_channel_distribution(customer_df: Any, cust_segment: Any) -> Any:
    ...

def plot_segment_sales_barchart(customers_df: Any, orders_df: Any, start_date: Any, end_date: Any) -> Any:
    ...

def plot_sales_trend_by_segment(customers_df: Any, orders_df: Any, start_date: Any, end_date: Any, cust_segment: Any) -> Any:
    ...

def plot_calendar_heatmap(customers_df: Any, orders_df: Any, start_date: Any, end_date: Any, cust_segment: Any, metric: Any) -> Any:
    ...

def plot_top_n_products(lineitems_df: pd.DataFrame, orders_df: pd.DataFrame, customers_df: pd.DataFrame, start_date: str, end_date: str, cust_segment: Optional[str], n: int, figsize: Tuple[int, int]) -> Any:
    ...

def plot_churn_rate_by_segment(orders_df: Any, customers_df: Any, customer_id_col: Any, segment_col: Any, figsize: Any, title: Any, xlabel: Any, ylabel: Any, show_counts: Any, xlim_padding: Any, datetime_col: Any, monetary_value_col: Any) -> Any:
    ...

def plot_clv_by_segment(orders_df: Any, customers_df: Any, customer_id_col: Any, datetime_col: Any, monetary_value_col: Any, segment_col: Any, figsize: Any, title: Any, xlabel: Any, ylabel: Any, show_counts: Any, return_data: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import calendar
import matplotlib
import matplotlib.pyplot
import numpy
import pandas
import seaborn
import matplotlib.patches
import typing