# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

CUSTOMER_VIP = 'VIP Customers'
CUSTOMER_LOYAL = 'Loyal Customers'
CUSTOMER_PROMISING = 'New Promising Customers'
CUSTOMER_AT_RISK = 'At Risk Customers'

__name__ = ...



# No other modules used internally, no implicit dependencies.
