# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from . import data_preparation
from pymc_extras.prior import Prior
from pymc_marketing import clv
from rfm_analyzer import RFMAnalyzer
from typing import Any
import logging

def run_customer_segmentation(customers_df: Any, orders_df: Any, analysis_date: Any) -> Any:
    ...

def prepare_rfm_data(orders_df: Any, customer_id_col: Any, datetime_col: Any, monetary_value_col: Any, time_unit: Any) -> Any:
    ...

def build_customer_behaviour_model(rfm_data: Any, train_amount: Any) -> Any:
    ...

def build_monetary_model(rfm_data: Any, train_amount: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import pymc_extras
import pymc_extras.prior
import pymc_marketing
import pymc_marketing.clv
import logging