# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import pandas

def build_customer_metrics(orders_df: Any, customers_df: Any, analysis_date: Any) -> Any:
    ...

def prepare_segment_data(customers_df: Any, orders_df: Any, start_date: Any, end_date: Any, cust_segment: Any) -> Any:
    ...

def prepare_purchase_data(lineitems_df: pd.DataFrame, orders_df: pd.DataFrame, customers_df: pd.DataFrame) -> pd.DataFrame:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import pandas