# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from . import constants
from typing import Any
from typing_extensions import Self
import pandas

class RFMAnalyzer:
    def __init__(self: Self, analysis_date: Any) -> None: ...
    def calculate_rfm_scores(self: Self, df_customer: Any) -> Any: ...
    def create_segments(self: Self, df_rfm: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import pandas